add project from trial
hafedEfheij/code-review-documentation pull request #1
Opened 2023-03-04 23:42 UTC by hafedEfheij

2023-03-04 23:53 UTC, hafedEfheij reviewed
STATUS: CHANGES REQUIRED 
Hello @hafedEfheij ,
I am Hafed.

Great job reaching this far While you have done a great job working on this project, there are some issues that you still need to work on to go to the next project.  
keep up the good work, You are almost there, 
![360_F_360671329_ylgnpA3vttPoNPWrXTtfe6kuc7f6E0g2](https://user-images.githubusercontent.com/63527271/205706347-9d4b8ff4-3dbe-4f95-80ad-f8df351f6dc9.jpg)

2023-03-04 23:53 UTC, hafedEfheij commented on babel/index.babel
> +// Once you have read the above messages, you can delete all comments.
for better readability, Please do not leave unused code or files

2023-03-04 23:53 UTC, hafedEfheij commented on index.html
> +      <nav id="navbar">
I think it would be better to wrap the nav in a semantic HTML tag

2023-03-04 23:53 UTC, hafedEfheij commented on index.html
> +        </header>
Nice use of the header, I suggest defining it with id or class so you can design more easily with CSS

2023-03-04 23:53 UTC, hafedEfheij commented on index.html
> +            <h1>section5</h1>
I think I would be better if you use h2 for the design propose

2023-03-04 23:53 UTC, hafedEfheij commented on index.html
> +      <nav id="navbar">
I think it would be better to wrap the nav in a semantic HTML tag

2023-03-05 00:00 UTC, jerryowusu commented on index.html
> +      <nav id="navbar">
For each requested changes, kindly provide a reason why that change needs to be made. This will help the student know why the changes are to be made, hence it will be easier to implement them. :+1:

2023-03-05 00:00 UTC, jerryowusu commented on index.html
> +            <h1>section5</h1>
For each requested changes, kindly provide a reason why that change needs to be made. This will help the student know why the changes are to be made, hence it will be easier to implement them. :+1:

2023-03-05 00:01 UTC, jerryowusu commented on index.html
> +      <nav id="navbar">
For each requested changes, kindly provide a reason why that change needs to be made. This will help the student know why the changes are to be made, hence it will be easier to implement them. :wink:

2023-03-05 00:04 UTC, jerryowusu requested changes
Hi @hafedEfheij , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost there](https://user-images.githubusercontent.com/65233860/222934479-691acd72-0444-4bac-87de-60b18d627ac4.jpg)


## Highlights
Gave at least 2 inline review comments :+1: 
Polite and kind comments :+1: 

## Required Changes ♻️

- [ ] For each requested changes, kindly provide a reason why that change needs to be made. This will help the student know why the changes are to be made, hence it will be easier to implement them. :+1: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-05 00:23 UTC, hafedEfheij commented on index.html
> +      <nav id="navbar">
Thank you for your review . Done I have updated the reviews

2023-03-05 00:32 UTC, AbayomiOlaoye approved these changes
Hi @hafedEfheij :wave: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- You communicate your suggestions politely :heavy_check_mark: 
- Your sentences are readable and easy to understand :heavy_check_mark: 
- You gave reasons for changes :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-05 00:33 UTC, merged